### PR TITLE
feat: schema loader

### LINKED ISSUE #840: Flexible Input Formats for Schema in Testing Validation File
We are seeking to expand the capabilities of our testing validation file structure. Our current schema configuration is structured as follows:

```yaml
schema: |-
    entity user {}
    entity role {
        relation assignee @user
    }

relationships:
    - dashboard:project-progress#view@role:admin#assignee

attributes:

scenarios:
    - name: "User Dashboard View Permissions"
      // ... scenario details ...
    // ... other scenarios ...
```

### Proposed Enhancement

**Enhancement Overview:** I propose we expand the schema field to accept input as a simple string text representing either a URL or a file path, in addition to the current direct string input.

**Objective:** This enhancement is intended to increase flexibility in how we input and manage schema data, allowing us to adapt to various testing requirements more effectively.

New Input Options with Format Specifications

**1. URL Input (String Text):**
```yaml
schema: "http://example.com/schema/user-role-schema"
```
For URL input, the system should be capable of fetching the schema as a plain text file from the specified URL.

2. File Path Input (String Text):
```yaml
schema: "/path/to/local/schema-file.txt"
```
Here, the input is a simple string representing the file path, and the system should read the schema as a plain text file from this location.

3. Direct String Input (Current Method):
```yaml
schema: |-
    entity user {}
    entity role {
        relation assignee @user
    }
```
This method remains unchanged, where the schema is input directly as a YAML formatted string.

**Benefits**

**Enhanced Flexibility:** Supports different methods of inputting schema data.
**Streamlined Testing:** Facilitates easier switching between schemas, enhancing testing efficiency.
**User-Friendly:** Provides multiple intuitive options for defining schemas.

### PR DESCRIPTION
**Pull request by neo773**
Adds SchemaLoader to load schema over HTTP, Fs Path

https://github.com/Permify/permify/assets/62795688/decb9cef-637f-4deb-af70-523efb425bba

/claim #840
/closes #840

### CODE REVIEW

**Comment by tolgaOzen** [comment]
Hello @neo773 , thank you for your contribution. Could you please write the unit tests as a final step?

**Comment by neo773** [comment]
@tolgaOzen 
Added the unit tests, also you might wanna change the load from HTTP URL to a something owned by you currently it's pointing to a gist by me.

SCR-20231118-ozrt

**Comment by tolgaOzen** [comment]
Can you also update the commit names according to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)?

**Comment by neo773** [comment]
@tolgaOzen 
Shall I make a new PR with all commits merged into one?
I'm not sure how to change the commit messages for multiple commits as I've never done it.

**Comment by neo773** [comment]
@tolgaOzen 
Closing this as I made a new PR https://github.com/Permify/permify/pull/849
I failed miserably at trying to rename the commit messages

**Pull request closed without merging**
