### PR TITLE
runbundle and test

### PR DESCRIPTION
**Pull request by Rutik7066**
/claim #875
Runbundle and Test

Screenshot_20231220_144524-1

### CODE REVIEW

**Comment by Rutik7066** [comment]
Hey @tolgaOzen  
Quality / Test with Coverage (pull_request)  failed is it something related to my Code ? i don't idea what it is.

**Comment by Rutik7066** [comment]
Hey @tolgaOzen could you review the PR.

**Comment by Rutik7066** [comment]
Hey @tolgaOzen my previous PR is closed due misconfigurations in my git while submitting PR so i have made another PR in this PR i have implemented runbundle function and test for it test ran successfully but after submitting PR one check is failed could you please review and reply it is something wrong in my code or is it something else?

**Comment by Rutik7066** [comment]
Hey, @tolgaOzen  implementation is done could you please take a look and let me know if anything needs to be implemented?

**Comment by Rutik7066** [comment]
hey @tolgaOzen I need your help to resolve this issue.

**Comment by Rutik7066** [comment]
Hi @EgeAytin i am having problem figuring out what's wrong in my code. This GitHub test failed. I have asked tolgaOzen but he haven't respond may be he is busy or traveling. So i need your guidance what wrong with code so that i can resolve this issue and claim remaining bounty.

**Comment by tolgaOzen** [comment]
Hello @Rutik7066, I am reviewing it and will get back to you.

**Comment by Rutik7066** [comment]
Thank @tolgaOzen. I thought you were busy.

**Comment by Rutik7066** [comment]
Hey @Rutik7066 is it perfect?

**Pull request closed without merging**
