### PR TITLE
feat: support for both HTTP and gRPC protocols in meter/logging/tracing

### LINKED ISSUE #1090: Support exporting OTLP over gRPC
**Is your feature request related to a problem? Please describe.**
The OTLP exporter for tracers, logs and metrics currently are hardcoded to use HTTP. It would be great if it optionally supported gRPC as well:

https://github.com/Permify/permify/blob/c4e26ce817144687671abee51c0d0df3b40736e5/pkg/telemetry/meterexporters/otlp.go#L11-L15

**Describe the solution you'd like**
1. expand the meter/logging/tracing config with a sub object called `oltp` containing `protocol` (if this is the only option that supports gRPC. If supported by multiple libraries I'd keep it at the top level.
2. branch on above option (which defaults to http) and invoke the different exporter.

**Describe alternatives you've considered**
Stick with HTTP

### PR DESCRIPTION
**Pull request by vikashsprem**
/claim #1090 
/close #1090 

Add support for both HTTP and gRPC protocols in meter/logging/tracing in meter/logging/tracing exports

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Protocol` configuration field for log, tracing, and metrics exporters, allowing users to specify communication protocols (HTTP or gRPC) for enhanced data transmission.
	- Enhanced exporter creation functions to accept the `protocol` parameter, increasing flexibility in configuring log, tracer, and meter exporters.

- **Bug Fixes**
	- Improved error handling for unsupported protocol inputs in OTLP exporter functions, ensuring clearer feedback to users.

- **Documentation**
	- Updated documentation to reflect changes made to configuration options and exporter functionalities.

### CODE REVIEW

**Comment by vikashsprem** [comment]
@tolgaOzen Please review this PR. Thank you.

**Comment by vikashsprem** [comment]
Now I have fixed the inconsistency reviewed by [coderabbitai](https://github.com/apps/coderabbitai)

**Comment by vikashsprem** [comment]
@tolgaOzen , There are two falling test case: vercel and Coverage / Test with Coverage. is it from my side?

**Comment by tolgaOzen** [comment]
hello @vikashsprem , thank you for your contribution 🚀

**Pull request merged**
