### PR TITLE
feat: add JSON logging

### LINKED ISSUE #929: Add JSON Output Option for Logger Configuration
**Description:**
There's a need to enhance the logger configuration in the /pkg/cmd/serve.go file to support JSON output. Currently, the logger is set up with a text handler, but it would be beneficial to have an option for JSON output for better integration with log management tools that work more efficiently with JSON.

**Current Implementation:**
```go
// /pkg/cmd/serve.go
logger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
	Level: getLogLevel(cfg.Log.Level),
}))
```

**Proposed Changes:**
1. Modify the Log struct in /pkg/cmd/serve.go to include an Output field, allowing the configuration to specify the desired output format (e.g., text or JSON).

```go
// /pkg/cmd/serve.go
// Log contains configuration for logging.
Log struct {
    Level  string `mapstructure:"level"` // Logging level
    Output string `mapstructure:"output"` // Logging output format, e.g., text, json
}
```

2. Update the logger initialization to use this new Output field to determine whether to use a text handler or a JSON handler.

**Additional Context:**
The addition of a JSON output option will make the logger more versatile and suitable for a variety of logging environments, especially where JSON-formatted logs are preferred for their structured format and ease of parsing.

### PR DESCRIPTION
**Pull request by neo773**
/closes #929
/claim #929

### CODE REVIEW

**Comment by tolgaOzen** [comment]
Hello @neo773, can you add this as a flag to the server flags?

**Comment by neo773** [comment]
@tolgaOzen 
Are you talking about serve.go?
So a CLI flag to set override the config output?

**Comment by tolgaOzen** [comment]
It will be sufficient to add it here as log-output:
```
// pkg/cmd/flags/serve.go
// LOG
flags.String("log-level", conf.Log.Level, "real-time logs of authorization. Permify uses zerolog as a logger")
if err := viper.BindPFlag("logger.level", flags.Lookup("log-level")); err != nil {
	panic(err)
}
if err := viper.BindEnv("logger.level", "PERMIFY_LOG_LEVEL"); err != nil {
	panic(err)
}
```

**Comment by neo773** [comment]
@tolgaOzen 
Pushed a new commit, can you check now?

**Comment by tolgaOzen** [comment]
Looks great. Thank you for your contribution.

**Pull request merged**
